// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tvo.Infraestructura.AccesoDatos;

public partial class brands
{
    public int idBrands { get; set; }

    public string brand { get; set; }

    public virtual ICollection<budget> budget { get; set; } = new List<budget>();

    public virtual ICollection<models> models { get; set; } = new List<models>();
}