// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tvo.Infraestructura.AccesoDatos;

public partial class budgetStatement
{
    public int idBudgetStatement { get; set; }

    public string descriptionStatement { get; set; }

    public virtual ICollection<budget> budget { get; set; } = new List<budget>();
}