// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace tvo.Infraestructura.AccesoDatos;

public partial class budget
{
    public int idBudget { get; set; }

    public int? idWorkOrder { get; set; }

    public int? idTransportData { get; set; }

    public int? idBudgetStatement { get; set; }

    public int? idBrands { get; set; }

    public DateOnly? issueDate { get; set; }

    public DateOnly? validUntil { get; set; }

    public string comments { get; set; }
    [JsonIgnore]
    public virtual brands idBrandsNavigation { get; set; }
    [JsonIgnore]
    public virtual budgetStatement idBudgetStatementNavigation { get; set; }
    [JsonIgnore]
    public virtual transportData idTransportDataNavigation { get; set; }
    [JsonIgnore]
    public virtual workOrder idWorkOrderNavigation { get; set; }
}