// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace tvo.Infraestructura.AccesoDatos;

public partial class client
{
    public int idClient { get; set; }

    public string nui { get; set; }

    public string firstName { get; set; }

    public string lastName { get; set; }

    public string phone { get; set; }

    public string mail { get; set; }

    public string addressClient { get; set; }

    public string passwordClient { get; set; }

    public int? idClientStatus { get; set; }
    [JsonIgnore]
    public virtual clientStatus idClientStatusNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<transportData> transportData { get; set; } = new List<transportData>();
}