// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tvo.Infraestructura.AccesoDatos;

public partial class clientStatus
{
    public int idClientStatus { get; set; }

    public string clientStatus1 { get; set; }

    public virtual ICollection<client> client { get; set; } = new List<client>();
}