// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tvo.Infraestructura.AccesoDatos;

public partial class cooperative
{
    public int idCooperative { get; set; }

    public string nameCooperative { get; set; }

    public virtual ICollection<transportData> transportData { get; set; } = new List<transportData>();
}