// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace tvo.Infraestructura.AccesoDatos;

public partial class employee
{
    public int idEmployee { get; set; }

    public int? idSpecialties { get; set; }

    public int? idRolEmployee { get; set; }

    public string nui { get; set; }

    public string firstName { get; set; }

    public string lastName { get; set; }

    public string phone { get; set; }

    public string addressEmp { get; set; }

    public string mail { get; set; }
    [JsonIgnore]
    public virtual rolEmployee idRolEmployeeNavigation { get; set; }
    [JsonIgnore]
    public virtual specialties idSpecialtiesNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<workOrder> workOrder { get; set; } = new List<workOrder>();
}