// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tvo.Infraestructura.AccesoDatos;

public partial class models
{
    public int idModels { get; set; }

    public int? idBrands { get; set; }

    public string models1 { get; set; }

    public virtual brands idBrandsNavigation { get; set; }
}