// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tvo.Infraestructura.AccesoDatos;

public partial class orderDetails
{
    public int idOrderDetails { get; set; }

    public int? idWorkOrder { get; set; }

    public int? idService { get; set; }

    public virtual services idServiceNavigation { get; set; }

    public virtual workOrder idWorkOrderNavigation { get; set; }
}