// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tvo.Infraestructura.AccesoDatos;

public partial class orderStatus
{
    public int idOrderStatus { get; set; }

    public string orderStatus1 { get; set; }

    public virtual ICollection<workOrder> workOrder { get; set; } = new List<workOrder>();
}