// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace tvo.Infraestructura.AccesoDatos;

public partial class services
{
    public int idService { get; set; }
    public string descriptionServices { get; set; }
    [JsonIgnore]
    public virtual ICollection<orderDetails> orderDetails { get; set; } = new List<orderDetails>();
    [JsonIgnore]
    public virtual ICollection<servicePrice> servicePrice { get; set; } = new List<servicePrice>();
}