// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace tvo.Infraestructura.AccesoDatos;

public partial class servicePriceHistory
{
    public int idServicePriceHistory { get; set; }

    public int? idServicePrice { get; set; }

    public decimal? price { get; set; }

    public DateOnly? startDate { get; set; }

    public DateOnly? endDate { get; set; }

    public string changeBy { get; set; }
    [JsonIgnore]
    public virtual servicePrice idServicePriceNavigation { get; set; }
}