// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tvo.Infraestructura.AccesoDatos;

public partial class servicePrice
{
    public int idServicePrice { get; set; }

    public int? idService { get; set; }

    public decimal? price { get; set; }

    public virtual services idServiceNavigation { get; set; }

    public virtual ICollection<servicePriceHistory> servicePriceHistory { get; set; } = new List<servicePriceHistory>();
}