// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tvo.Infraestructura.AccesoDatos;

public partial class specialties
{
    public int idSpecialties { get; set; }

    public string specialty { get; set; }

    public virtual ICollection<employee> employee { get; set; } = new List<employee>();
}