// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tvo.Infraestructura.AccesoDatos;

public partial class transportData
{
    public int idTransportData { get; set; }

    public int? idTransport { get; set; }

    public int? idCooperative { get; set; }

    public int? idClient { get; set; }

    public string plate { get; set; }

    public int num { get; set; }

    public string chassis { get; set; }

    public virtual ICollection<budget> budget { get; set; } = new List<budget>();

    public virtual client idClientNavigation { get; set; }

    public virtual cooperative idCooperativeNavigation { get; set; }

    public virtual transport idTransportNavigation { get; set; }
}