// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tvo.Infraestructura.AccesoDatos;

public partial class workOrder
{
    public int idWorkOrder { get; set; }

    public int? idEmployee { get; set; }

    public int? idOrderStatus { get; set; }

    public string descriptionWO { get; set; }

    public DateOnly expires { get; set; }

    public virtual ICollection<budget> budget { get; set; } = new List<budget>();

    public virtual employee idEmployeeNavigation { get; set; }

    public virtual orderStatus idOrderStatusNavigation { get; set; }

    public virtual ICollection<orderDetails> orderDetails { get; set; } = new List<orderDetails>();
}